#******************************************************************************#
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: creek <marvin@42.fr>                       +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/11/25 19:40:05 by creek             #+#    #+#              #
#    Updated: 2018/11/25 19:43:29 by creek            ###   ########.fr        #
#                                                                              #
#******************************************************************************#

NAME = ft_display_file

SRCS = ./ft_display_file.c

FLAGS = -Wall -Werror -Wextra

all: $(NAME) 

$(NAME):
	gcc -o $(NAME) $(FLAGS) $(SRCS) 

clean:
	/bin/rm -f *.o

fclean: clean 
	/bin/rm -f $(NAME)	
